### ISSUE TITLE
Other Codes That May Be Wrong

### ISSUE THREAD

**Issue by WolfieeifloW** [BetweenWalls/filterbird#2]
I will list them as what the wiki has vs what your code has them as.
- skill_Inferno:"SK41" / "SK46"
- skill_Blaze:"SK46" / "SK41"

Also, just completely missing is:
- skill_Ice_Barrage:"SK369"
- skill_Combustion:"SK376"
- skill_Lesser_Hydra:"SK383"
- skill_Blood_Warp:"SK367"
- skill_Curse_Mastery:"SK374"
- skill_Dark_Pact:"SK381"
- skill_Holy_Nova:"SK364"
- skill_Holy_Light:"SK371"
- skill_Joust:"SK378"
- skill_Gust:"SK370"
- skill_Lightning_Sentry:"SK366"

There were other differences in my compare but I'm not sure how to categorize them, as some may just simply be naming convention between wiki and in-game files. Here is an image of the comparison anyway though:
![image](https://user-images.githubusercontent.com/40577712/175646238-c28d2d08-4c74-4c91-8b44-2d4acbe3d261.png)

And here is the raw text for each:
Left side, straight from Wiki (formatted to match your code): https://pastebin.com/WVL7NiHE
Right side, straight from your code: https://pastebin.com/N41KLcAE

**Comment by BetweenWalls** [comment]
Just pushed an update with Inferno/Blaze codes swapped to their correct codes for PD2, and added the missing skills as pointmod options. As far as I can tell from comparing those, all the skills that can be selected as pointmods should be accounted for now.
